frontend/controllers/ParserController.php
<?php


namespace frontend\controllers;


use core\entities\Certificate;
use core\entities\CertificateStatus;
use core\entities\File;
use core\helpers\CertificateHelper;
use core\helpers\FileHelper;
use core\services\parser\jobs\LoadJob;
use yii\filters\AccessControl;
use yii\web\Controller;

class ParserController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
        $certificates = [
            'types' => [],
            'status' => [],
        ];
        foreach (CertificateHelper::getStatusLabel() as $status => $label) {
            $count = Certificate::find()->where(['job' => $status])->count();
            if ($count) {
                $certificates['types'][$status] = [
                    'label' => $label,
                    'class' => CertificateHelper::getStatusClass($status),
                    'count' => $count
                ];
            }
        }

        foreach (CertificateStatus::map() as $id => $status) {
            $count = Certificate::find()->where(['status' => $id])->count();
            if ($count) {
                $certificates['status'][$id] = [
                    'label' => $status['label'],
                    'class' => 'label label-' . $status['class'],
                    'count' => $count
                ];
            }
        }


        $files = [
            'types' => [],
            'status' => [],
        ];
        foreach (FileHelper::getAlias() as $type => $label) {
            $count = File::find()->where(['type' => $type])->count();
            if ($count) {
                $files['types'][$type] = [
                    'label' => $label,
                    'count' => $count
                ];
            }
        }

        foreach (FileHelper::getStatusLabel() as $id => $label) {
            $count = File::find()->where(['status' => $id])->count();
            if ($count) {
                $files['status'][$id] = [
                    'label' => $label,
                    'class' => CertificateHelper::getStatusClass($id),
                    'count' => $count
                ];
            }
        }

        return $this->render('index', [
            'certificates' => $certificates,
            'files' => $files,
        ]);
    }

    public function actionStart()
    {
        $chunks = Certificate::getChunks([CertificateHelper::STATUS_LOADED, CertificateHelper::STATUS_COMPLETE]);

        foreach ($chunks as $ids) {
            \Yii::$app->queue->push(new LoadJob([
                'ids' => $ids,
            ]));
        }

        return $this->redirect(['/dashboard']);
    }

}

frontend/views/parser/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $certificates [] */
/* @var $files [] */


$this->title = 'Статистика';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success" href="<?=Url::to(['/parser/start']);?>">Запустить</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4>Лаборатории
                <small>по статусу</small>
            </h4>
            <table class="table">
                <?php foreach ($certificates['status'] as $certificate) : ?>
                    <tr>
                        <td><?= $certificate['label']; ?></td>
                        <td>
                            <span class="label <?= $certificate['class']; ?>"><?= $certificate['count']; ?></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>

            <hr>

            <h4>Лаборатории
                <small>по состоянию</small>
            </h4>
            <table class="table">
                <?php foreach ($certificates['types'] as $certificate) : ?>
                    <tr>
                        <td><?= $certificate['label']; ?></td>
                        <td>
                            <span class="label <?= $certificate['class']; ?>"><?= $certificate['count']; ?></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>

        <div class="col-md-6">
            <h4>Файлы
                <small>по типу</small>
            </h4>
            <table class="table">
                <?php foreach ($files['types'] as $file) : ?>
                    <tr>
                        <td><?= $file['label']; ?></td>
                        <td>
                            <span><?= $file['count']; ?></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>

            <hr>

            <h4>Файлы
                <small>по состоянию</small>
            </h4>
            <table class="table">
                <?php foreach ($files['status'] as $file) : ?>
                    <tr>
                        <td><?= $file['label']; ?></td>
                        <td>
                            <span class="label <?= $file['class']; ?>"><?= $file['count']; ?></span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>


</div>