frontend/controllers/CertificateController.php
<?php


namespace frontend\controllers;


use codemix\excelexport\ExcelFile;
use core\entities\Certificate;
use core\entities\CertificateSearch;
use core\entities\History;
use core\forms\certificate\CertificateEditForm;
use core\forms\DownloadForm;
use core\forms\LoadForm;
use core\helpers\CertificateHelper;
use core\services\csv\Exporter;
use core\services\importer\CsvImporter;
use core\services\parser\jobs\InitJob;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class CertificateController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $model = new CertificateSearch();
        $download = new DownloadForm();

        $dataProvider = $model->search(\Yii::$app->request->queryParams);

        if ($download->load(\Yii::$app->request->post())) {
            $download->save();

            $csv = new Exporter('ochki', $download->getListTitle());

            foreach ($dataProvider->query->with('structure')->batch(100) as $certificates) {
                /** @var Certificate $certificate */
                foreach ($certificates as $certificate) {
                    $csv->addProduct($certificate);
                }
            }
            $csv->close();

            \Yii::$app->response->headers->set('Pragma', 'no-cache');
            \Yii::$app->response->sendFile(\Yii::getAlias("@common/data/result.csv"), 'Выборка от ' . date('d.m.Y H:i:s') . '.csv');
            return true;
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
            'download' => $download
        ]);
    }


    public function actionUpdate($id)
    {
        $certificate = Certificate::find()->where(['id' => $id])->one();
        if (!$certificate) {
            throw new NotFoundHttpException('Сертификат не найден');
        }
        $form = new CertificateEditForm($certificate);

        return $this->render('update', [
                'model' => $form
            ]
        );
    }

    public function actionView($id)
    {
        $model = Certificate::find()->where(['id' => $id])->one();
        if (!$model) {
            throw new NotFoundHttpException('Страница не найдена');
        }

        $dataProvider = new ActiveDataProvider([
            'query' => History::find()->where(['cert_id' => $model->id]),
            'sort' => [
                'defaultOrder' => ['id' => SORT_DESC]
            ]
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }
}

frontend/views/certificate/import.php
<?php

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \core\forms\LoadForm */

$this->title = 'Импорт';
$this->params['breadcrumbs'][] = ['label' => 'Список АО', 'url' => ['/certificate/index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="certificate-load">
    <?php $form = ActiveForm::begin(['options' => [
        'enctype' => 'multipart/form-data'
    ]]); ?>

    <?= $form->field($model, 'file')->fileInput(); ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/certificate/index.php
<?php

use core\entities\Area;
use core\entities\Certificate;
use core\entities\CertificateSearch;
use core\entities\CertificateStatus;
use core\entities\Region;
use core\entities\Structure;
use core\forms\DownloadForm;
use core\helpers\CertificateHelper;
use core\helpers\HistoryHelper;
use yii\bootstrap\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $download DownloadForm */
/* @var $model CertificateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Список';
$this->params['breadcrumbs'][] = $this->title;

$this->registerJs("
$('.jsFilterCheck').on('click', function() {
  var isAll = $(this).data('all');
  $.each($('#downloadform-list input[type=\"checkbox\"]'), function(i, el) {
      $(el).attr(\"checked\", !isAll);
    });
  $(this).data('all', !isAll);
});


")

?>
<div class="certificate-index">
    <div class="row">
        <div class="col-md-12">
            <?php $form = ActiveForm::begin([
                'action' => 'index',
                'method' => 'get',
            ]); ?>
            <div class="box box-success collapsed-box">
                <div class="box-header">
                    <h3 class="box-title">
                        Поиск
                    </h3>
                    <div class="box-tools pull-right">
                        <?= Html::submitButton('<i class="fa fa-search text-blue"></i>', [
                            'class' => 'btn btn-default btn-sm',
                            'title' => 'Найти'
                        ]) ?>
                        <?= Html::a('<i class="fa fa-close text-red"></i>', ['index'], [
                            'class' => 'btn btn-default btn-sm',
                            'title' => 'Сбросить'
                        ]) ?>
                        <button type="button" class="btn btn-default btn-sm" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="history-search">
                        <?php $form = ActiveForm::begin([
                            'action' => ['index'],
                            'method' => 'get',
                        ]); ?>

                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'uid')->textInput() ?>
                                <?= $form->field($model, 'status')->checkboxList(CertificateStatus::getList()) ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model, 'regions')->dropDownList(Region::getList(),[
                                    'multiple' => 'multiple'
                                ]) ?>
                                <?= $form->field($model, 'areas')->dropDownList(Area::getList(), [
                                    'multiple' => 'multiple'
                                ]) ?>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field($model, 'type')->checkboxList(HistoryHelper::getLabels()) ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field($model, 'date_start')->widget(DatePicker::className(), [
                                    'language' => 'ru',
                                    'dateFormat' => 'dd.MM.yyyy',
                                    'options' => [
                                        'class' => 'form-control'
                                    ]
                                ]) ?>
                                <?= $form->field($model, 'date_end')->widget(DatePicker::className(), [
                                    'language' => 'ru',
                                    'dateFormat' => 'dd.MM.yyyy',
                                    'options' => [
                                        'class' => 'form-control'
                                    ]
                                ]) ?>
                            </div>
                        </div>
                        <?php ActiveForm::end(); ?>
                    </div>
                </div>

                <div class="box-footer">
                    <?= Html::submitButton('Найти', [
                        'class' => 'btn btn-primary',
                        'title' => 'Найти'
                    ]) ?>
                    <?= Html::a('Сбросить', ['index'], [
                        'class' => 'btn btn-default',
                        'title' => 'Сбросить'
                    ]) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-12">
            <?php $form = ActiveForm::begin([
                'method' => 'post',
            ]); ?>
            <div class="box box-success collapsed-box">
                <div class="box-header">
                    <h3 class="box-title">
                        Экспорт
                    </h3>
                    <div class="box-tools pull-right">
                        <?= Html::submitButton('<i class="fa fa-download text-blue"></i>', [
                            'class' => 'btn btn-default btn-sm',
                            'title' => 'Скачать'
                        ]) ?>
                        <button type="button" class="btn btn-default btn-sm jsFilterCheck">
                            <i class="fa fa-check"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm" data-widget="collapse">
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <?= $form->field($download, 'list', [

                    ])->checkboxList(Structure::getAttributeList(), [
                        'multiple' => 'multiple',
                    ]); ?>
                </div>
                <div class="box-footer">
                    <div class="form-group">
                        <?= Html::submitButton('Скачать', ['class' => 'btn btn-primary']) ?>
                    </div>
                </div>

            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

    <div class="box box-primary">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    [
                        'attribute' => 'id',
                        'format' => 'raw',
                        'value' => function (Certificate $certificate) {
                            return $certificate->link ?
                                Html::a($certificate->id, $certificate->url, ['target' => '_blank'])
                                : $certificate->id;
                        }
                    ],
                    [
                        'attribute' => 'uid',
                        'format' => 'raw',
                        'value' => function (Certificate $certificate) {
                            $span = Html::tag('div', $certificate->uid, [
                                'class' => 'btn btn-xs btn-' . $certificate->status->class,
                                'title' => $certificate->status->label,
                            ]);
                            return Html::a($span, ['/certificate/view', 'id' => $certificate->id]);
                        }
                    ],
                    [
                        'attribute' => 'updated_at',
                        'format' => 'raw',
                        'value' => function (Certificate $certificate) {
                            return Yii::$app->formatter->asDatetime($certificate->updated_at);
                        }
                    ],
                    [
                        'attribute' => 'region_id',
                        'format' => 'raw',
                        'value' => function (Certificate $certificate) use ($model) {
                            $result = '';
                            foreach ($certificate->regions as $area){
                                $result .= Html::tag('span', $area->title, [
                                        'class' => 'label label-' . ($model->hasSearchRegion($area->id) ? 'success' : 'default')
                                    ]) . ' ';
                            }
                            return $result;
                        }
                    ],
                    [
                        'header' => 'Объекты исследования',
                        'format' => 'raw',
                        'value' => function (Certificate $certificate) use ($model) {
                            $result = '';
                            foreach ($certificate->areas as $area){
                                $result .= Html::tag('span', $area->title, [
                                    'class' => 'label label-' . ($model->hasSearchArea($area->id) ? 'success' : 'default')
                                ]) . ' ';
                            }
                            return $result;
                        }
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

frontend/views/certificate/update.php
<?php

use core\forms\certificate\CertificateEditForm;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model CertificateEditForm */

$this->title = 'Редактирование сертификата ' . $model->certificate->uid;
$this->params['breadcrumbs'][] = ['label' => 'Список АО', 'url' => ['/certificate/index']];
$this->params['breadcrumbs'][] = ['label' => $model->certificate->uid, 'url' => ['/certificate/view', ['id' => $model->certificate->id]]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="box box-primary">
    <?php $form = Html::beginForm([
        'method' => 'post'
    ]); ?>


    <?php Html::endForm(); ?>
</div>

frontend/views/certificate/view.php
<?php

use core\entities\Certificate;
use core\entities\History;
use core\helpers\FileHelper;
use yii\bootstrap\Html;
use yii\grid\GridView;
use yii\helpers\Json;
use yii\helpers\VarDumper;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model Certificate */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = $model->uid;
$this->params['breadcrumbs'][] = ['label' => 'Список АО', 'url' => ['/certificate/index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-6">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Общая информация</h3>
            </div>
            <div class="box-body">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        [
                            'attribute' => 'uid',
                            'format' => 'raw',
                            'value' => Html::a($model->uid, $model->url, ['target' => '_blank'])
                        ],

                        'updated_at:datetime',
                        'status:raw',
                        [
                            'attribute' => 'regions',
                            'format' => 'raw',
                            'value' => function () use ($model) {
                                $result = '';
                                foreach ($model->regions as $region) {
                                    $result .= Html::tag('span', $region->title, [
                                            'class' => 'label label-default'
                                        ]) . ' ';
                                }
                                return $result;
                            }
                        ],
                        [
                            'attribute' => 'areas',
                            'format' => 'raw',
                            'value' => function () use ($model) {
                                $result = '';
                                foreach ($model->areas as $area) {
                                    $result .= Html::tag('span', $area->title, [
                                            'class' => 'label label-default'
                                        ]) . ' ';
                                }
                                return $result;
                            }
                        ]
                    ],
                ]) ?>
            </div>
        </div>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Список файлов</h3>
            </div>
            <div class="box-body">
                <table class="table">
                    <?php foreach ($model->files as $file) : ?>
                        <tr>
                            <td><?= FileHelper::getAlias($file->type); ?></td>
                            <td><?= $file->name; ?></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">История изменений</h3>
            </div>
            <div class="box-body">
                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        [
                            'attribute' => 'type',
                            'format' => 'raw',
                            'value' => function (History $history) {
                                return $history->name;
                            }
                        ],
                        'created_at:datetime',
                        [
                            'attribute' => 'data',
                            'format' => 'raw',
                            'value' => function (History $history) {
                                return $history->value;
                            }
                        ],

                    ],
                ]); ?>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Данные реестра</h3>
            </div>
            <div class="box-body table-responsive">
                <?php if ($model->structure) : ?>
                    <?= DetailView::widget([
                        'model' => $model->structure,
                        'attributes' => [
                            'type_al:ntext',
                            'type_ap:ntext',
                            'opf_ap:ntext',
                            'full_name_ap:ntext',
                            'short_name_ap:ntext',
                            'trade_name_ap:ntext',
                            'fio_ruk_ap:ntext',
                            'dol_ruk_ap:ntext',
                            'address_ap:ntext',
                            'address_delo_ap:ntext',
                            'phone_ap:ntext',
                            'email_ap:ntext',
                            'ogrn:ntext',
                            'inn_ap:ntext',
                            'full_name_al:ntext',
                            'short_name_al:ntext',
                            'fio_ruk_al:ntext',
                            'address_al:ntext',
                            'phone_al:ntext',
                            'email_al:ntext',
                            'website_al:ntext',
                            'lab_al:ntext',
                            'own_lab_al:ntext',
                            'expert_al:ntext',
                            'fio_rab_al:ntext',
                            'obl_akk_al:ntext',
                            'status:ntext',
                            'reg_number:ntext',
                            'on_reg_dat:ntext',
                            'off_att_akk_dat:ntext',
                            'akkred_order_num:ntext',
                            'akkred_order_dat:ntext',
                            'akkred_exp:ntext',
                            'izm_att_akk:ntext',
                            'ts:ntext',
                            'gk:ntext',
                        ],
                    ]) ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>