frontend/controllers/ImportController.php
<?php


namespace frontend\controllers;


use core\entities\Region;
use core\entities\Structure;
use core\forms\ImportFilterForm;
use core\forms\ImportStructureForm;
use core\jobs\FilterImportJob;
use core\jobs\StructureImportJob;
use core\repositories\CertificateRepository;
use core\services\importer\structure\Importer;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\UploadedFile;

class ImportController extends Controller
{


    /** @var CertificateRepository */
    private $certificates;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    public function actionFilter()
    {
        $form = new ImportFilterForm();
        if($form->load(\Yii::$app->request->post()) && $form->file = UploadedFile::getInstance($form, 'file')) {
            if($form->save()) {
                \Yii::$app->queue->push(new FilterImportJob([
                    'file' => $form->filePath
                ]));
            }

            $this->redirect('/certificate/index');
        }

        return $this->render('filter', [
            'model' => $form
        ]);
    }


    public function actionStructure()
    {
        $form = new ImportStructureForm();
        if($form->load(\Yii::$app->request->post()) && $form->file = UploadedFile::getInstance($form, 'file')) {
            if($form->save()) {
                \Yii::$app->queue->push(new StructureImportJob([
                    'file' => $form->filePath
                ]));
            }

            $this->redirect('/certificate/index');
        }

        return $this->render('structure', [
            'model' => $form
        ]);
    }
}

frontend/views/layouts/auth.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>

frontend/views/layouts/header.php
<?php
use frontend\widgets\task\TaskList;use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg"></span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
                <?= TaskList::widget();?>
            </ul>
        </div>
    </nav>
</header>

frontend/views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">
        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'items' => [
                    ['label' => 'Лаборатории', 'options' => ['class' => 'header']],
                    ['label' => 'Список', 'icon' => 'list', 'url' => ['/certificate/index']],
                    ['label' => 'Файлы', 'icon' => 'file-o', 'url' => ['/file/index']],

                    ['label' => 'Импорт', 'options' => ['class' => 'header']],
                    ['label' => 'Фильтры', 'icon' => 'filter', 'url' => ['/import/filter']],
                    ['label' => 'Данные АО', 'icon' => 'database', 'url' => ['/import/structure']],


                    ['label' => 'Настройки', 'options' => ['class' => 'header']],

                    ['label' => 'Панель управления', 'icon' => 'dashboard', 'url' => ['/dashboard']],
                    ['label' => 'Объекты исследования', 'icon' => 'sitemap', 'url' => ['/area']],
                ],
            ]
        ) ?>
    </section>
</aside>

frontend/views/layouts/main.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


frontend\assets\AppAsset::register($this);
dmstr\web\AdminLteAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render(
        'header',
        ['directoryAsset' => $directoryAsset]
    ) ?>

    <?= $this->render(
        'left',
        ['directoryAsset' => $directoryAsset]
    )
    ?>

    <?= $this->render(
        'content',
        ['content' => $content, 'directoryAsset' => $directoryAsset]
    ) ?>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>