frontend/controllers/AreaController.php
<?php

namespace frontend\controllers;

use Yii;
use core\entities\Area;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AreaController implements the CRUD actions for Area model.
 */
class AreaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Lists all Area models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Area::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }



    /**
     * Updates an existing Area model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Area model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Area the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Area::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/area/index.php
<?php

use core\entities\Area;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Объекты исследования';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="area-index">

    <div class="box box-success">
        <div class="box-header">
            <div class="box-tools pull-right">
                <?= Html::a('<i class="fa fa-plus text-blue"></i>', ['create'], [
                    'class' => 'btn btn-default btn-sm',
                    'title' => 'Создать'
                ]) ?>
            </div>
        </div>
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    'alias',
                    [
                        'attribute' => 'title',
                        'format' => 'raw',
                        'value' => function (Area $area) {
                            return Html::a($area->title, ['/area/update', 'id' => $area->id]);
                        }
                    ],

                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{delete}'
                    ],
                ],
            ]); ?>
        </div>

        <div class="box-footer">
            <?= Html::a('Создать', ['create'], [
                'class' => 'btn btn-primary',
            ]) ?>
        </div>
    </div>


</div>

frontend/views/area/update.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model core\entities\Area */

$this->title = 'Редактирование объекта исследования: ' .$model->title;
$this->params['breadcrumbs'][] = ['label' => 'Объекты исследования', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирования';
?>
<div class="area-update">

    <?php $form = ActiveForm::begin(); ?>
    <div class="box box-success">
        <div class="box-header">
            <div class="box-tools pull-right">
                <?= Html::submitButton('<i class="fa fa-plus text-blue"></i>', [
                    'class' => 'btn btn-save btn-sm',
                    'title' => 'Сохранить'
                ]) ?>
            </div>
        </div>
        <div class="box-body">
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        </div>

        <div class="box-footer">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>